(* File automatically generated by the configure script *)
let libdir = "/gnatmail/sandbox/a2c2/x86_64-darwin/alt-ergo/install/lib"
let pluginsdir = "/gnatmail/sandbox/a2c2/x86_64-darwin/alt-ergo/install/lib/alt-ergo/plugins"
let preludesdir = "/gnatmail/sandbox/a2c2/x86_64-darwin/alt-ergo/install/share/alt-ergo/preludes"
let datadir = "/gnatmail/sandbox/a2c2/x86_64-darwin/alt-ergo/install/share"
let mandir = "/gnatmail/sandbox/a2c2/x86_64-darwin/alt-ergo/install/man"
